### ISSUE TITLE
Getting the error "Contract has not been deployed to detected network (network/artifact mismatch)"

### ISSUE THREAD

**Issue by hi0310** [didil/stone-dapp#2]
Whenever I try to run this application locally, I get the error above. 
I tried the following commands:

truffle compile
truffle migrate

however, have not been able to resolve this issue.
Any idea why this may be?

**Comment by didil** [comment]
so this project was built using truffle v3 , if you want to use truffle v4 you need to update the truffle-contract package in package.json to 3.x

**Comment by hi0310** [comment]
Hi,

Thanks for your response. 

I have updated the line in package.json
"truffle-contract" to ^4.0.6, however, have not been able to resolve the issue either. 

Are there any other reasons why I may be facing this error?

**Comment by didil** [comment]
the latest truffle contract version is 3.0.3 so you need to switch to that https://www.npmjs.com/package/truffle-contract , then run npm install and truffle migrate

**Comment by hi0310** [comment]
It seems that the HashStore is not getting deployed to the network correctly as the following error is shown:

"HashStore has not been deployed to detected network (network/artifact mismatch)"

Do you have any idea why this may be?

**Comment by hi0310** [comment]
When truffle test is run, it seems to have no problem. However, when the application is started using npm run start, the error message "HashStore has not been deployed to the detected network (network/artifact mismatch)" is shown. 

When "Recent Submissions" and "Fetch Submission" is pressed, it displays the textboxes along with the texts fetch submission and recent submissions. However, when Submit text is pressed, nothing seems to be happening.

**Comment by hi0310** [comment]
When "Submit Text" button is pressed, the following error is shown:

SubmitForm.js:23 Uncaught TypeError: Cannot read property 'price' of undefined
    at SubmitForm.loadPrice (SubmitForm.js:23)
    at SubmitForm.componentWillMount (SubmitForm.js:19)
    at ReactCompositeComponent.js:345
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:344)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at Object.updateChildren (ReactChildReconciler.js:119)
    at ReactDOMComponent._reconcilerUpdateChildren (ReactMultiChild.js:204)
    at ReactDOMComponent._updateChildren (ReactMultiChild.js:308)

**Comment by hilbert25** [comment]
I find there is something wrong with my migrations/2_deploy_contracts.js. I fix it and resolve the bug.

**Comment by voidiker66** [comment]
I am getting the same error as in the title. What is the change in migrations/2_deploy_contracts.js that fixed the bug?

When clicking the "Submit Text"  and "Recent Submissions" buttons, I am getting this error instead - 
TypeError: this.props.hashStoreContractInstance is undefined

EDIT:
I resolved this issue by editing the getWeb3.js file to make a workaround for testing solely on localhost.

`import Web3 from 'web3'

let getWeb3 = new Promise(function (resolve, reject) {
  // Wait for loading completion to avoid race conditions with web3 injection timing.
  window.addEventListener('load', function () {
    let web3 = window.web3;

    // Checking if Web3 has been injected by the browser (Mist/MetaMask)
    if (typeof web3 !== 'undefined') {
      // Use Mist/MetaMask's provider.
      /*web3 = new Web3(web3.currentProvider);
      console.log('Injected web3 detected.');
    } else if (process.env.NODE_ENV === "development") {
      // Fallback to localhost if no web3 injection.*/
      let provider = new Web3.providers.HttpProvider('http://localhost:9545');
      web3 = new Web3(provider);
      console.log('No web3 instance injected, using Local web3.');
    }
    else {
      return reject(new Error('No web3 instance injected.'));
    }

    web3.eth.getAccounts((err, accounts) => {
      if (err) {
        return reject(err);
      }

      web3.eth.defaultAccount = accounts[0];
      console.log('Using account:', web3.eth.defaultAccount);
      resolve({web3: web3});
    });
  });
});

export default getWeb3`

I commented out the lines where it dynamically assigns the web3 provider and inserted my own local server.

**Comment by ShabanGomaa** [comment]
in your "truffle-config.js" or "truffle.js" file add networks section:
networks: {
    ganache: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*"
    },
    development: {
      host: "127.0.0.1",
      port: 9545,
      network_id: "*" // Match any network id
    }
  }

then tuffle develop, compile 
and run the command "truffle migrate --network ganache"

**Comment by lfpantoja** [comment]
How to solve HASHSTORECONTRACTINSTANCE not defined????

**Comment by AnvarHadja** [comment]
I was able to resolve this. Try this:

- run command "npm audit fix" in your root project folder via terminal
- then run "npm install" . Should be sucessfullly install all dependencies
- run "truflle migrate"
- run "truffle console"
- Finally check by running via JS "ProjectName.deployed()"

 Let us know please if this is resolved your problem
